language: node_js
node_js:
  - 9
  - 8
  - 7
  - 6
  - 6.1
  - 5
  - 5.11

os:
  - linux
  - osx

notifications:
  webhooks: https://app.fossa.io/hooks/travisci

git:
  depth: 1

before_script:
   - npm dedupe

script:
  - echo $TRAVIS_BUILD_DIR
  - echo $(pwd)
  - npm test

after_script:
  - npm run posttest:ci:coverage:codacy

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"
