 approvals:
  # PR needs at least 1 approval
  minimum: 1
  # approval = comment that matches this regex
  pattern: "^(:\\+1:|👍)$"
  veto:
    # veto/blocking a PR = comment that matches this regex
    pattern: "^(:\\-1:|👎)$"
  # note that `from` is by default empty,
  # accepting any matching comment as approval
  from:
    # commenter must be either one of:
    orgs:
      # a public democracy-ia org member
      # (any org in here counts)
      - democracy-ia
    # OR a collaborator of the repo
    collaborators: true
    # OR one of these guys
    users:
      - gregswindle
      - rnickme
  # you can define groups from which you
  # require approvals
  groups:
    # this defines a "maintainers" approver group
    maintainers:
      # where the approval check will fail if there
      # is less than 1 approval from it
      minimum: 1
      # the group includes every public democracy-ia org member
      from:
        orgs:
          - democracy-ia
commit:
  message:
    # note that there are no default patterns for commit messages
    # has to begin with hash # and at least one number
    patterns:
      - "^(build|chore|ci|docs|feat|fix|perf|refactor|spike|style|test)\(\S+\):\s{1}(.*){3,50}$"
        # OR
      - "^(revert): \b[0-9a-f]{7,40}\b$"
autobranch:
  # things in curly brackets are variables that
  # will be replaced. possible variables:
  # - number: the issue number
  # - title: the issue title
  # - labels: the labels of the issue at opening time
  pattern: "GH-{number}-{title}"
  # restrict branch name to maximum this many characters
  length: 65
