version: 1.0.{build}

environment:
  matrix:
    - nodejs_version: '9'
    - nodejs_version: '8'
    - nodejs_version: '7'
    - nodejs_version: '6'
    - nodejs_version: '6.1'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i npm@latest -g
  - npm install

matrix:
  fast_finish: true

build: off

shallow_clone: true

clone_depth: 1

test_script:
  - node --version
  - npm --version
  - cd %APPVEYOR_BUILD_FOLDER%
  # - npm run test:windows
  - C:\projects\govinfo-link-js\node_modules\.bin\nyc C:\projects\govinfo-link-js\node_modules\.bin\mocha C:\projects\govinfo-link-js\test\**\*.spec.js
