/**
 * govinfo-link-js
 * <p>The <strong>govinfo</strong> Link Service provides services for developers and webmasters to access content and metadata on <strong>govinfo</strong>. Current and planned services include a link service, list service, and search service. Please contact <a href=\"https://www.gpo.gov/askgpo/\">askGPO</a> for additional information about current or planned services.</p> <p>The link service is used to create embedded links to content and metadata on <strong>govinfo</strong> and is currently enabled for the collections below. The collection code is listed in parenthesis after each collection name, and the available queries are listed below each collection. More information about each query is provided on the individual collection page.</p>
 *
 * OpenAPI spec version: 0.5.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.

    define(['ApiClient'], factory)
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.

    module.exports = factory(require('../ApiClient'))
  } else {
    // Browser globals (root is window)

    if (!root.govinfoLinkService) {
      root.govinfoLinkService = {
      }
    }
    root.govinfoLinkService.CodeOfFederalRegulations = factory(root.govinfoLinkService.ApiClient)
  }
}(this, (ApiClient) => {
  /**
   * CodeOfFederalRegulationsCFR service.
   * @module api/CodeOfFederalRegulations
   * @version 0.5.0
   */

  /**
   * Constructs a new CodeOfFederalRegulations. 
   * 
   * @alias module:api/CodeOfFederalRegulations
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  const exports = function (apiClient) {
    this.apiClient = apiClient || ApiClient.instance

    /**
     * Callback function to receive the result of the cfrFetchUsingGET operation.
     * @callback module:api/CodeOfFederalRegulations~cfrFetchUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Query: title number, part number, section number, year OR most recent
     * 
     * @param {Number} titlenum Title number. Sample value is 3.
     * @param {string} partnum Part number. Sample value is 100
     * @param {Object} opts Optional parameters
     * @param {String} opts.sectionnum This is the section number. Sample value is 1. If section number is not provided the entire part will be returned.
     * @param {String} opts.year This is the four digit numerical year OR mostrecent. If year is not provided the most recent version of the CFR section or part is returned. Default is most recent. Sample value is 2011.
     * @param {module:model/String} opts.linkType This is the format of the returned document. Default is pdf. Other values are xml, mods, premis, details, context, related.
     * @param {module:api/CodeOfFederalRegulations~cfrFetchUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    this.cfrFetchUsingGET = function (titlenum, partnum, opts, callback) {
      opts = opts || {
      }
      const postBody = null

      // Verify the required parameter 'titlenum' is set

      if (titlenum === undefined || titlenum === null) {
        throw new Error("Missing the required parameter 'titlenum' when calling cfrFetchUsingGET")
      }

      // Verify the required parameter 'partnum' is set

      if (partnum === undefined || partnum === null) {
        throw new Error("Missing the required parameter 'partnum' when calling cfrFetchUsingGET")
      }

      const pathParams = {
        titlenum,
        partnum
      }
      const queryParams = {
        'sectionnum': opts.sectionnum,
        'year': opts.year,
        'link-type': opts.linkType
      }
      const collectionQueryParams = {
      }
      const headerParams = {
      }
      const formParams = {
      }

      const authNames = []
      const contentTypes = ['application/json']
      const accepts = ['*/*']
      const returnType = Object

      return this.apiClient.callApi(
        '/cfr/{titlenum}/{partnum}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      )
    }
  }

  return exports
}))
