/**
 * Govinfo-link-js
 * <p>The <strong>govinfo</strong> Link Service provides services for developers and webmasters to access content and metadata on <strong>govinfo</strong>. Current and planned services include a link service, list service, and search service. Please contact <a href=\"https://www.gpo.gov/askgpo/\">askGPO</a> for additional information about current or planned services.</p> <p>The link service is used to create embedded links to content and metadata on <strong>govinfo</strong> and is currently enabled for the collections below. The collection code is listed in parenthesis after each collection name, and the available queries are listed below each collection. More information about each query is provided on the individual collection page.</p>
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.

    define(['ApiClient'], factory)
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.

    module.exports = factory(require('../ApiClient'))
  } else {
    // Browser globals (root is window)

    if (!root.govinfoLinkService) {
      root.govinfoLinkService = {
      }
    }
    root.govinfoLinkService.StatutesAtLarge = factory(root.govinfoLinkService.ApiClient)
  }
}(this, (ApiClient) => {
  /**
   * StatutesAtLargeSTATUTE service.
   * @module api/StatutesAtLarge
   * @version 1.0.0
   */

  /**
   * Constructs a new StatutesAtLarge. 
   * 
   * @alias module:api/StatutesAtLarge
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  const exports = function (apiClient) {
    this.apiClient = apiClient || ApiClient.instance

    /**
     * Callback function to receive the result of the statuteTypeFetchUsingGET operation.
     * @callback module:api/StatutesAtLarge~statuteTypeFetchUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Query: Congress, law type, law number.
     * 
     * @param {number} congress - This is the numerical Congress number. Sample value is 108.
     * @param {module:model/String} lawtype - This is the law type. Laws can either be public laws or private laws. Values are public, private.
     * @param {number} lawnum - This is the numerical law number. Laws are numbered consecutively within each law type within a Congress. Sample value is 481.
     * @param {Object} opts - Optional parameters.
     * @param {module:model/String} opts.linkType - This is the format of the returned document. Default is pdf. Other values are html, mods, premis, details, context.
     * @param {module:api/StatutesAtLarge~statuteTypeFetchUsingGETCallback} callback The callback function, accepting three arguments: Error, data, response
     * data is of type: {@link Object}.
     */
    this.statuteTypeFetchUsingGET = function (congress, lawtype, lawnum, opts, callback) {
      opts = opts || {
      }
      const postBody = null

      // Verify the required parameter 'congress' is set

      if (congress === undefined || congress === null) {
        throw new Error(`Missing the required parameter 'congress' when calling statuteTypeFetchUsingGET'`)
      }

      // Verify the required parameter 'lawtype' is set

      if (lawtype === undefined || lawtype === null) {
        throw new Error(`Missing the required parameter 'lawtype' when calling statuteTypeFetchUsingGET'`)
      }

      // Verify the required parameter 'lawnum' is set

      if (lawnum === undefined || lawnum === null) {
        throw new Error(`Missing the required parameter 'lawnum' when calling statuteTypeFetchUsingGET'`)
      }

      const pathParams = {
        congress,
        lawtype,
        lawnum
      }
      const queryParams = {
        'link-type': opts.linkType
      }
      const collectionQueryParams = {
      }
      const headerParams = {
      }
      const formParams = {
      }

      const authNames = []
      const contentTypes = ['application/json']
      const accepts = ['*/*']
      const returnType = Object

      return this.apiClient.callApi(
        '/statute/{congress}/{lawtype}/{lawnum}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      )
    }

    /**
     * Callback function to receive the result of the statuteVolumeFetchUsingGET operation.
     * @callback module:api/StatutesAtLarge~statuteVolumeFetchUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Query: Volume, page number.
     * 
     * @param {number} volume - This is the numerical volume number. Sample value is 118.
     * @param {number} page - This is the numerical page number. Statutes at Large pages are numbered consecutively within a volume. Note: When multiple granules are contained on a page, content and metadata for the last granule on the page will be returned. Recommend selecting PDF link-type to return content for all granules on a page. Sample value is 3910.
     * @param {Object} opts - Optional parameters.
     * @param {module:model/String} opts.linkType - This is the format of the returned document. Default is pdf. Other values are html, mods, premis, details, context.
     * @param {module:api/StatutesAtLarge~statuteVolumeFetchUsingGETCallback} callback The callback function, accepting three arguments: Error, data, response
     * data is of type: {@link Object}.
     */
    this.statuteVolumeFetchUsingGET = function (volume, page, opts, callback) {
      opts = opts || {
      }
      const postBody = null

      // Verify the required parameter 'volume' is set

      if (volume === undefined || volume === null) {
        throw new Error(`Missing the required parameter 'volume' when calling statuteVolumeFetchUsingGET'`)
      }

      // Verify the required parameter 'page' is set

      if (page === undefined || page === null) {
        throw new Error(`Missing the required parameter 'page' when calling statuteVolumeFetchUsingGET'`)
      }

      const pathParams = {
        volume,
        page
      }
      const queryParams = {
        'link-type': opts.linkType
      }
      const collectionQueryParams = {
      }
      const headerParams = {
      }
      const formParams = {
      }

      const authNames = []
      const contentTypes = ['application/json']
      const accepts = ['*/*']
      const returnType = Object

      return this.apiClient.callApi(
        '/statute/{volume}/{page}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      )
    }
  }

  return exports
}))
