/**
 * Govinfo-link-js
 * <p>The <strong>govinfo</strong> Link Service provides services for developers and webmasters to access content and metadata on <strong>govinfo</strong>. Current and planned services include a link service, list service, and search service. Please contact <a href=\"https://www.gpo.gov/askgpo/\">askGPO</a> for additional information about current or planned services.</p> <p>The link service is used to create embedded links to content and metadata on <strong>govinfo</strong> and is currently enabled for the collections below. The collection code is listed in parenthesis after each collection name, and the available queries are listed below each collection. More information about each query is provided on the individual collection page.</p>
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function (factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.

    define([
      'ApiClient',
      'api/CodeOfFederalRegulations',
      'api/CompilationOfPresidentialDocuments',
      'api/CongressionalBills',
      'api/CongressionalCalendars',
      'api/CongressionalCommitteePrints',
      'api/CongressionalDocuments',
      'api/CongressionalHearings',
      'api/CongressionalRecordDaily',
      'api/CongressionalReports',
      'api/FederalRegister',
      'api/PublicAndPrivateLaws',
      'api/StatutesAtLarge',
      'api/UnitedStatesCode'
    ], factory)
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.

    const ApiClient = require('./ApiClient')
    const CodeOfFederalRegulations = require('./api/CodeOfFederalRegulations')
    const CompilationOfPresidentialDocuments = require('./api/CompilationOfPresidentialDocuments')
    const CongressionalBills = require('./api/CongressionalBills')
    const CongressionalCalendars = require('./api/CongressionalCalendars')
    const CongressionalCommitteePrints = require('./api/CongressionalCommitteePrints')
    const CongressionalDocuments = require('./api/CongressionalDocuments')
    const CongressionalHearings = require('./api/CongressionalHearings')
    const CongressionalRecordDaily = require('./api/CongressionalRecordDaily')
    const CongressionalReports = require('./api/CongressionalReports')
    const FederalRegister = require('./api/FederalRegister')
    const PublicAndPrivateLaws = require('./api/PublicAndPrivateLaws')
    const StatutesAtLarge = require('./api/StatutesAtLarge')
    const UnitedStatesCode = require('./api/UnitedStatesCode')
    // const { promisify } = require('util')
    const pify = require('pify')

    // 5.0.
    ApiClient.prototype.callApi = pify(ApiClient.prototype.callApi)
    // 5.1.
    CodeOfFederalRegulations.prototype = pify(CodeOfFederalRegulations)
    // 5.2.
    CodeOfFederalRegulations.prototype = pify(CodeOfFederalRegulations)
    // 5.3.
    CompilationOfPresidentialDocuments.prototype = pify(CompilationOfPresidentialDocuments)
    
    CongressionalBills.prototype = pify(CongressionalBills)
    
    CongressionalCalendars.prototype =  pify(CongressionalCalendars)
    
    CongressionalCommitteePrints.prototype =  pify(CongressionalCommitteePrints)
    
    CongressionalDocuments.prototype =  pify(CongressionalDocuments)
    
    CongressionalHearings.prototype =  pify(CongressionalHearings)
    
    CongressionalRecordDaily.prototype =  pify(CongressionalRecordDaily)
    
    CongressionalReports.prototype =  pify(CongressionalReports)
    
    FederalRegister.prototype =  pify(FederalRegister)
    
    PublicAndPrivateLaws.prototype =  pify(PublicAndPrivateLaws)
    
    StatutesAtLarge.prototype =  pify(StatutesAtLarge)
    
    UnitedStatesCode.prototype =  pify(UnitedStatesCode)

    module.exports = factory(
      ApiClient,
      CodeOfFederalRegulations,
      CompilationOfPresidentialDocuments,
      CongressionalBills,
      CongressionalCalendars,
      CongressionalCommitteePrints,
      CongressionalDocuments,
      CongressionalHearings,
      CongressionalRecordDaily,
      CongressionalReports,
      FederalRegister,
      PublicAndPrivateLaws,
      StatutesAtLarge,
      UnitedStatesCode
    )
  }
}((ApiClient, CodeOfFederalRegulations, CompilationOfPresidentialDocuments, CongressionalBills, CongressionalCalendars, CongressionalCommitteePrints, CongressionalDocuments, CongressionalHearings, CongressionalRecordDaily, CongressionalReports, FederalRegister, PublicAndPrivateLaws, StatutesAtLarge, UnitedStatesCode) => {
  /**
   * PThe_stronggovinfostrong_Link_Service_provides_services_for_developers_and_webmasters_to_access_content_and_metadata_on_stronggovinfostrong__Current_and_planned_services_include_a_link_service_list_service_and_search_service__Please_contact_a_hrefhttpswww_gpo_govaskgpoaskGPOa_for_additional_information_about_current_or_planned_services_p_pThe_link_service_is_used_to_create_embedded_links_to_content_and_metadata_on_stronggovinfostrong_and_is_currently_enabled_for_the_collections_below__The_collection_code_is_listed_in_parenthesis_after_each_collection_name_and_the_available_queries_are_listed_below_each_collection__More_information_about_each_query_is_provided_on_the_individual_collection_page_p.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * const govinfoLinkService = require('index'); // See note below*.
   * const xxxSvc = new govinfoLinkService.XxxApi(); // Allocate the API class we're going to use.
   * const yyyModel = new govinfoLinkService.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * const zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * const xxxSvc = new govinfoLinkService.XxxApi(); // Allocate the API class we're going to use.
   * const yyy = new govinfoLinkService.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * const zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */

  const exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */

    ApiClient,

    /**
     * The CodeOfFederalRegulations service constructor.
     * @property {module:api/CodeOfFederalRegulations}
     */

    CodeOfFederalRegulations,

    /**
     * The CompilationOfPresidentialDocuments service constructor.
     * @property {module:api/CompilationOfPresidentialDocuments}
     */

    CompilationOfPresidentialDocuments,

    /**
     * The CongressionalBills service constructor.
     * @property {module:api/CongressionalBills}
     */

    CongressionalBills,

    /**
     * The CongressionalCalendars service constructor.
     * @property {module:api/CongressionalCalendars}
     */

    CongressionalCalendars,

    /**
     * The CongressionalCommitteePrints service constructor.
     * @property {module:api/CongressionalCommitteePrints}
     */

    CongressionalCommitteePrints,

    /**
     * The CongressionalDocuments service constructor.
     * @property {module:api/CongressionalDocuments}
     */

    CongressionalDocuments,

    /**
     * The CongressionalHearings service constructor.
     * @property {module:api/CongressionalHearings}
     */

    CongressionalHearings,

    /**
     * The CongressionalRecordDaily service constructor.
     * @property {module:api/CongressionalRecordDaily}
     */

    CongressionalRecordDaily,

    /**
     * The CongressionalReports service constructor.
     * @property {module:api/CongressionalReports}
     */

    CongressionalReports,

    /**
     * The FederalRegister service constructor.
     * @property {module:api/FederalRegister}
     */

    FederalRegister,

    /**
     * The PublicAndPrivateLaws service constructor.
     * @property {module:api/PublicAndPrivateLaws}
     */

    PublicAndPrivateLaws,

    /**
     * The StatutesAtLarge service constructor.
     * @property {module:api/StatutesAtLarge}
     */

    StatutesAtLarge,

    /**
     * The UnitedStatesCode service constructor.
     * @property {module:api/UnitedStatesCode}
     */

    UnitedStatesCode
  }

  return exports
}))
